name: Deploy to WordPress.org
on:
  release:
    types: [released]
jobs:
  tag:
    name: GATTAI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          npm run build
      - name: HASSHIN
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ secrets.SLUG }}
